name: ci

on:
  push:
    branches:
      - master   # change to 'main' only if your default branch is 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}      # you added DOCKER_USER variable
          password: ${{ secrets.DOCKER_PAT }}    # you added DOCKER_PAT secret

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "football-builder"           # your Build Cloud builder name

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: "mariam333/football-web:latest" # your Docker Hub repo/tag
